version: '2'

services:
  api:
    container_name: 'tipals-auth'
    image: 'tipals-auth'
    build:
      context: .
      dockerfile: Dockerfile.Auth
    ports:
    - "5000:5000"
    depends_on:
     - "sqlinux"
    networks:
    - tipals-auth-network
     
  sqlinux:
    container_name: 'sqlinux'
    image: microsoft/mssql-server-linux
    volumes_from:
    - data
    environment:
      #POSTGRES_DB: featuretoggles
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "f117ab2#dulekavaz"
    networks:
      - tipals-auth-network
  data:
    image: cogniteev/echo
    command: echo 'Data Container'
    volumes:
    - /var/lib/sqlinux/data
    networks:
      - tipals-auth-network

networks:
  tipals-auth-network:
    driver: bridge